In [1]:
import datetime
import numpy as np
import pandas as pd

from utils import (
    fetch_aeti,
    fetch_ret,
    fetch_rainfall,
    fetch_irrigations,
    fetch_kc,
    calculate_daily_water_delta,
    calculate_daily_water,
    calculate_pam_root_zone,
    calculate_pam_depletion_root_zone,
    calculate_moisture_level,
    irrigation_trigger,
)

In [2]:
# Constants
ROOT_DEPTH = np.array(([0.1] * 14) + [0.11 + 0.01 * i for i in range(90)] + [1.0] * 265) 
THETA_10 = 0.196
FIELD_CAPACITY_PER_FOOT = THETA_10 * 0.3048
PAM_FLOOR = 0.096
THETA_1500 = 0.055

In [3]:
planting_date = datetime.date(2025, 12, 10)

In [4]:

# Fetch data

aeti = fetch_aeti(planting_date)
aeti

Using cached WAPOR-3.L1-AETI-D.2025-11-D3.tif
Using cached WAPOR-3.L1-AETI-D.2025-12-D1.tif
Using cached WAPOR-3.L1-AETI-D.2025-12-D2.tif
Using cached WAPOR-3.L1-AETI-D.2025-12-D3.tif
Using cached WAPOR-3.L1-AETI-D.2026-01-D1.tif
Using cached WAPOR-3.L1-AETI-D.2026-01-D2.tif
Using cached WAPOR-3.L1-AETI-D.2026-01-D3.tif
Fetched 7 files from 2025-11-21 to 2026-01-21

,date,A-2,A-1,A-3,A-4,B-1,B-2,B-4,B-3,C-1,C-2,D-3,C-3,C-4,D-1,D-2,D-4
0,2025-11-21,0.1000,0.1,0.100000,0.1,0.100000,0.10,0.100,0.10,0.1,0.100000,0.1,0.100000,0.10,0.1,0.100000,0.100000
1,2025-11-22,0.1000,0.1,0.100000,0.1,0.100000,0.10,0.100,0.10,0.1,0.100000,0.1,0.100000,0.10,0.1,0.100000,0.100000
2,2025-11-23,0.1000,0.1,0.100000,0.1,0.100000,0.10,0.100,0.10,0.1,0.100000,0.1,0.100000,0.10,0.1,0.100000,0.100000
3,2025-11-24,0.1000,0.1,0.100000,0.1,0.100000,0.10,0.100,0.10,0.1,0.100000,0.1,0.100000,0.10,0.1,0.100000,0.100000
4,2025-11-25,0.1000,0.1,0.100000,0.1,0.100000,0.10,0.100,0.10,0.1,0.100000,0.1,0.100000,0.10,0.1,0.100000,0.100000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67,2026-01-27,0.4375,0.6,0.466667,0.4,0.511111,0.45,0.525,0.55,0.5,0.483333,0.5,0.433333,0.35,0.5,0.383333,0.433333
68,2026-01-28,0.4375,0.6,0.466667,0.4,0.511111,0.45,0.525,0.55,0.5,0.483333,0.5,0.433333,0.35,0.5,0.383333,0.433333
69,2026-01-29,0.4375,0.6,0.466667,0.4,0.511111,0.45,0.525,0.55,0.5,0.483333,0.5,0.433333,0.35,0.5,0.383333,0.433333
70,2026-01-30,0.4375,0.6,0.466667,0.4,0.511111,0.45,0.525,0.55,0.5,0.483333,0.5,0.433333,0.35,0.5,0.383333,0.433333
71,2026-01-31,0.4375,0.6,0.466667,0.4,0.511111,0.45,0.525,0.55,0.5,0.483333,0.5,0.433333,0.35,0.5,0.383333,0.433333

In [5]:

rainfall = fetch_rainfall(planting_date)
with pd.option_context("display.max_rows", None):
    display(rainfall)

Using cached WAPOR-3.L1-PCP-E.2025-11-26.tif
Using cached WAPOR-3.L1-PCP-E.2025-11-27.tif
Using cached WAPOR-3.L1-PCP-E.2025-11-28.tif
Using cached WAPOR-3.L1-PCP-E.2025-11-29.tif
Using cached WAPOR-3.L1-PCP-E.2025-11-30.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-01.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-02.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-03.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-04.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-05.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-06.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-07.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-08.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-09.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-10.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-11.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-12.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-13.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-14.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-15.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-16.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-17.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-18.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-19.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-20.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-21.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-22.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-23.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-24.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-25.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-26.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-27.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-28.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-29.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-30.tif
Using cached WAPOR-3.L1-PCP-E.2025-12-31.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-01.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-02.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-03.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-04.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-05.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-06.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-07.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-08.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-09.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-10.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-11.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-12.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-13.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-14.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-15.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-16.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-17.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-18.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-19.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-20.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-21.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-22.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-23.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-24.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-25.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-26.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-27.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-28.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-29.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-30.tif
Using cached WAPOR-3.L1-PCP-E.2026-01-31.tif
Using cached WAPOR-3.L1-PCP-E.2026-02-01.tif
Using cached WAPOR-3.L1-PCP-E.2026-02-02.tif
Using cached WAPOR-3.L1-PCP-E.2026-02-03.tif
Using cached WAPOR-3.L1-PCP-E.2026-02-04.tif
Using cached WAPOR-3.L1-PCP-E.2026-02-05.tif
Using cached WAPOR-3.L1-PCP-E.2026-02-06.tif
Using cached WAPOR-3.L1-PCP-E.2026-02-07.tif
Using cached WAPOR-3.L1-PCP-E.2026-02-08.tif
Using cached WAPOR-3.L1-PCP-E.2026-02-09.tif
Using cached WAPOR-3.L1-PCP-E.2026-02-10.tif
Fetched 77 files from 2025-11-26 to 2026-02-10

,date,A-2,A-1,A-3,A-4,B-1,B-2,B-4,B-3,C-1,C-2,D-3,C-3,C-4,D-1,D-2,D-4
0,2025-11-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
1,2025-11-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
2,2025-11-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
3,2025-11-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
4,2025-11-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
5,2025-12-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
6,2025-12-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
7,2025-12-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
8,2025-12-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
9,2025-12-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
10,2025-12-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
11,2025-12-07,7.9,7.9,7.9,7.9,7.9,7.9,7.9,7.9,7.9,9.10,7.9,7.9,9.10,7.9,7.9,7.80
12,2025-12-08,1.3,1.3,1.3,1.3,1.3,1.3,1.3,1.3,1.3,1.15,1.3,1.3,1.15,1.3,1.3,1.75
13,2025-12-09,2.8,2.8,2.8,2.8,2.8,2.8,2.8,2.8,2.8,2.70,2.8,2.8,2.70,2.8,2.8,2.70
14,2025-12-10,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.15,0.1,0.1,0.15,0.1,0.1,0.10
15,2025-12-11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
16,2025-12-12,25.1,25.1,25.1,25.1,25.1,25.1,25.1,25.1,25.1,25.95,25.1,25.1,25.95,25.1,25.1,23.50
17,2025-12-13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
18,2025-12-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
19,2025-12-15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
20,2025-12-16,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.65,1.8,1.8,1.65,1.8,1.8,2.35
21,2025-12-17,7.4,7.4,7.4,7.4,7.4,7.4,7.4,7.4,7.4,8.80,7.4,7.4,8.80,7.4,7.4,10.25
22,2025-12-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.05
23,2025-12-19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
24,2025-12-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
25,2025-12-21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
26,2025-12-22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
27,2025-12-23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
28,2025-12-24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
29,2025-12-25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
30,2025-12-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
31,2025-12-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
32,2025-12-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
33,2025-12-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
34,2025-12-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
35,2025-12-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
36,2026-01-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
37,2026-01-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
38,2026-01-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
39,2026-01-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
40,2026-01-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
41,2026-01-06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
42,2026-01-07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
43,2026-01-08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
44,2026-01-09,4.8,4.8,4.8,4.8,4.8,4.8,4.8,4.8,4.8,4.80,4.8,4.8,4.80,4.8,4.8,3.80
45,2026-01-10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
46,2026-01-11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
47,2026-01-12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
48,2026-01-13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
49,2026-01-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
50,2026-01-15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
51,2026-01-16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
52,2026-01-17,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
53,2026-01-18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
54,2026-01-19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
55,2026-01-20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
56,2026-01-21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
57,2026-01-22,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,1.00,0.9,0.9,1.00,0.9,0.9,0.90
58,2026-01-23,2.1,2.1,2.1,2.1,2.1,2.1,2.1,2.1,2.1,1.75,2.1,2.1,1.75,2.1,2.1,2.05
59,2026-01-24,13.3,13.3,13.3,13.3,13.3,13.3,13.3,13.3,13.3,14.05,13.3,13.3,14.05,13.3,13.3,14.00
60,2026-01-25,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.2,1.60,1.2,1.2,1.60,1.2,1.2,1.50
61,2026-01-26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
62,2026-01-27,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
63,2026-01-28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
64,2026-01-29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
65,2026-01-30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
66,2026-01-31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
67,2026-02-01,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
68,2026-02-02,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
69,2026-02-03,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
70,2026-02-04,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
71,2026-02-05,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.00,0.0,0.0,0.00
72,2026-02-06,3.4,3.4,3.4,3.4,3.4,3.4,3.4,3.4,3.4,3.05,3.4,3.4,3.05,3.4,3.4,3.50
73,2026-02-07,0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.8,0.95,0.8,0.8,0.95,0.8,0.8,0.75
74,2026-02-08,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.1,0.05,0.1,0.1,0.05,0.1,0.1,0.10
75,2026-02-09,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.9,0.70,0.9,0.9,0.70,0.9,0.9,0.95
76,2026-02-10,1.6,1.6,1.6,1.6,1.6,1.6,1.6,1.6,1.6,1.80,1.6,1.6,1.80,1.6,1.6,1.45

In [6]:

ret = fetch_ret(planting_date)
ret

Using cached WAPOR-3.L1-RET-E.2025-11-26.tif
Using cached WAPOR-3.L1-RET-E.2025-11-27.tif
Using cached WAPOR-3.L1-RET-E.2025-11-28.tif
Using cached WAPOR-3.L1-RET-E.2025-11-29.tif
Using cached WAPOR-3.L1-RET-E.2025-11-30.tif
Using cached WAPOR-3.L1-RET-E.2025-12-01.tif
Using cached WAPOR-3.L1-RET-E.2025-12-02.tif
Using cached WAPOR-3.L1-RET-E.2025-12-03.tif
Using cached WAPOR-3.L1-RET-E.2025-12-04.tif
Using cached WAPOR-3.L1-RET-E.2025-12-05.tif
Using cached WAPOR-3.L1-RET-E.2025-12-06.tif
Using cached WAPOR-3.L1-RET-E.2025-12-07.tif
Using cached WAPOR-3.L1-RET-E.2025-12-08.tif
Using cached WAPOR-3.L1-RET-E.2025-12-09.tif
Using cached WAPOR-3.L1-RET-E.2025-12-10.tif
Using cached WAPOR-3.L1-RET-E.2025-12-11.tif
Using cached WAPOR-3.L1-RET-E.2025-12-12.tif
Using cached WAPOR-3.L1-RET-E.2025-12-13.tif
Using cached WAPOR-3.L1-RET-E.2025-12-14.tif
Using cached WAPOR-3.L1-RET-E.2025-12-15.tif
Using cached WAPOR-3.L1-RET-E.2025-12-16.tif
Using cached WAPOR-3.L1-RET-E.2025-12-17.tif
Using cached WAPOR-3.L1-RET-E.2025-12-18.tif
Using cached WAPOR-3.L1-RET-E.2025-12-19.tif
Using cached WAPOR-3.L1-RET-E.2025-12-20.tif
Using cached WAPOR-3.L1-RET-E.2025-12-21.tif
Using cached WAPOR-3.L1-RET-E.2025-12-22.tif
Using cached WAPOR-3.L1-RET-E.2025-12-23.tif
Using cached WAPOR-3.L1-RET-E.2025-12-24.tif
Using cached WAPOR-3.L1-RET-E.2025-12-25.tif
Using cached WAPOR-3.L1-RET-E.2025-12-26.tif
Using cached WAPOR-3.L1-RET-E.2025-12-27.tif
Using cached WAPOR-3.L1-RET-E.2025-12-28.tif
Using cached WAPOR-3.L1-RET-E.2025-12-29.tif
Using cached WAPOR-3.L1-RET-E.2025-12-30.tif
Using cached WAPOR-3.L1-RET-E.2025-12-31.tif
Using cached WAPOR-3.L1-RET-E.2026-01-01.tif
Using cached WAPOR-3.L1-RET-E.2026-01-02.tif
Using cached WAPOR-3.L1-RET-E.2026-01-03.tif
Using cached WAPOR-3.L1-RET-E.2026-01-04.tif
Using cached WAPOR-3.L1-RET-E.2026-01-05.tif
Using cached WAPOR-3.L1-RET-E.2026-01-06.tif
Using cached WAPOR-3.L1-RET-E.2026-01-07.tif
Using cached WAPOR-3.L1-RET-E.2026-01-08.tif
Using cached WAPOR-3.L1-RET-E.2026-01-09.tif
Using cached WAPOR-3.L1-RET-E.2026-01-10.tif
Using cached WAPOR-3.L1-RET-E.2026-01-11.tif
Using cached WAPOR-3.L1-RET-E.2026-01-12.tif
Using cached WAPOR-3.L1-RET-E.2026-01-13.tif
Using cached WAPOR-3.L1-RET-E.2026-01-14.tif
Using cached WAPOR-3.L1-RET-E.2026-01-15.tif
Using cached WAPOR-3.L1-RET-E.2026-01-16.tif
Using cached WAPOR-3.L1-RET-E.2026-01-17.tif
Using cached WAPOR-3.L1-RET-E.2026-01-18.tif
Using cached WAPOR-3.L1-RET-E.2026-01-19.tif
Using cached WAPOR-3.L1-RET-E.2026-01-20.tif
Using cached WAPOR-3.L1-RET-E.2026-01-21.tif
Using cached WAPOR-3.L1-RET-E.2026-01-22.tif
Using cached WAPOR-3.L1-RET-E.2026-01-23.tif
Using cached WAPOR-3.L1-RET-E.2026-01-24.tif
Using cached WAPOR-3.L1-RET-E.2026-01-25.tif
Using cached WAPOR-3.L1-RET-E.2026-01-26.tif
Using cached WAPOR-3.L1-RET-E.2026-01-27.tif
Using cached WAPOR-3.L1-RET-E.2026-01-28.tif
Using cached WAPOR-3.L1-RET-E.2026-01-29.tif
Using cached WAPOR-3.L1-RET-E.2026-01-30.tif
Using cached WAPOR-3.L1-RET-E.2026-01-31.tif
Using cached WAPOR-3.L1-RET-E.2026-02-01.tif
Using cached WAPOR-3.L1-RET-E.2026-02-02.tif
Using cached WAPOR-3.L1-RET-E.2026-02-03.tif
Using cached WAPOR-3.L1-RET-E.2026-02-04.tif
Using cached WAPOR-3.L1-RET-E.2026-02-05.tif
Using cached WAPOR-3.L1-RET-E.2026-02-06.tif
Using cached WAPOR-3.L1-RET-E.2026-02-07.tif
Using cached WAPOR-3.L1-RET-E.2026-02-08.tif
Using cached WAPOR-3.L1-RET-E.2026-02-09.tif
Using cached WAPOR-3.L1-RET-E.2026-02-10.tif
Using cached WAPOR-3.L1-RET-E.2026-02-11.tif
Fetched 78 files from 2025-11-26 to 2026-02-11

,date,A-2,A-1,A-3,A-4,B-1,B-2,B-4,B-3,C-1,C-2,D-3,C-3,C-4,D-1,D-2,D-4
0,2025-11-26,3.7,3.7,3.7,3.7,3.7,3.7,3.7,3.7,3.7,3.7,3.7,3.7,3.7,3.7,3.7,3.7
1,2025-11-27,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6
2,2025-11-28,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0,3.0
3,2025-11-29,2.6,2.6,2.6,2.6,2.6,2.6,2.6,2.6,2.6,2.6,2.6,2.6,2.6,2.6,2.6,2.6
4,2025-11-30,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
73,2026-02-07,3.2,3.2,3.2,3.2,3.2,3.2,3.2,3.2,3.2,3.2,3.2,3.2,3.2,3.2,3.2,3.2
74,2026-02-08,3.2,3.2,3.2,3.2,3.2,3.2,3.2,3.2,3.2,3.2,3.2,3.2,3.2,3.2,3.2,3.2
75,2026-02-09,4.5,4.5,4.5,4.5,4.5,4.5,4.5,4.5,4.5,4.5,4.5,4.5,4.5,4.5,4.5,4.5
76,2026-02-10,4.6,4.6,4.6,4.6,4.6,4.6,4.6,4.6,4.6,4.6,4.6,4.6,4.6,4.6,4.6,4.6
77,2026-02-11,3.5,3.5,3.5,3.5,3.5,3.5,3.5,3.5,3.5,3.5,3.5,3.5,3.5,3.5,3.5,3.5

In [7]:
kc = fetch_kc()
kc

,date,A-1,A-2,A-3,A-4,B-1,B-2,B-3,B-4,C-1,C-2,C-3,C-4,D-1,D-2,D-3,D-4
0,2025-11-15,0.30,0.3,0.3,0.3,0.30,0.3,0.30,0.30,0.3,0.3,0.3,0.3,0.30,0.3,0.30,0.30
1,2025-11-16,0.30,0.3,0.3,0.3,0.30,0.3,0.30,0.30,0.3,0.3,0.3,0.3,0.30,0.3,0.30,0.30
2,2025-11-17,0.30,0.3,0.3,0.3,0.30,0.3,0.30,0.30,0.3,0.3,0.3,0.3,0.30,0.3,0.30,0.30
3,2025-11-18,0.30,0.3,0.3,0.3,0.30,0.3,0.30,0.30,0.3,0.3,0.3,0.3,0.30,0.3,0.30,0.30
4,2025-11-19,0.30,0.3,0.3,0.3,0.30,0.3,0.30,0.30,0.3,0.3,0.3,0.3,0.30,0.3,0.30,0.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101,2026-02-24,0.63,0.3,0.3,0.3,0.58,0.3,0.61,0.64,0.3,0.3,0.3,0.3,0.63,0.3,0.60,0.60
102,2026-02-25,0.64,0.3,0.3,0.3,0.59,0.3,0.62,0.65,0.3,0.3,0.3,0.3,0.64,0.3,0.61,0.61
103,2026-02-26,0.65,0.3,0.3,0.3,0.60,0.3,0.63,0.66,0.3,0.3,0.3,0.3,0.65,0.3,0.62,0.62
104,2026-02-27,0.66,0.3,0.3,0.3,0.61,0.3,0.64,0.67,0.3,0.3,0.3,0.3,0.66,0.3,0.63,0.63
105,2026-02-28,0.67,0.3,0.3,0.3,0.62,0.3,0.65,0.68,0.3,0.3,0.3,0.3,0.67,0.3,0.64,0.64

In [8]:
field_ids = list(range(37,53))
print(field_ids)
field_names = ["D-1", "B-3", "A-3", "A-2", "A-1", "D-3", "D-2", "C-2", "C-1", "C-3", "C-4", "A-4", "B-1", "B-2", "B-4", "D-4"]

[37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52]

In [9]:
from dotenv import load_dotenv

load_dotenv()

irrigations = fetch_irrigations(
    field_ids=field_ids,
    field_names=field_names,
)

irrigations

    field_name        date  amount_mm
0          A-3  2025-12-25        8.0
1          B-3  2025-12-25        8.0
2          A-2  2025-12-25        8.0
3          B-1  2025-12-25        8.0
4          A-4  2025-12-23       10.0
..         ...         ...        ...
347        B-4  2026-02-11        8.0
348        B-2  2026-02-11        8.0
349        A-2  2026-02-11        8.0
350        A-3  2026-02-11        8.0
351        A-4  2026-02-11        8.0

[352 rows x 3 columns]

In [10]:
# Calculate daily water delta
df = calculate_daily_water_delta(irrigations, kc, rainfall, ret)

with pd.option_context("display.max_rows", None):
    display(df)

mean ret: {'A-2': np.float64(3.6571428571428575), 'A-1': np.float64(3.6571428571428575), 'A-3': np.float64(3.6571428571428575), 'A-4': np.float64(3.6571428571428575), 'B-1': np.float64(3.6571428571428575), 'B-2': np.float64(3.6571428571428575), 'B-4': np.float64(3.6571428571428575), 'B-3': np.float64(3.6571428571428575), 'C-1': np.float64(3.6571428571428575), 'C-2': np.float64(3.6571428571428575), 'D-3': np.float64(3.6571428571428575), 'C-3': np.float64(3.6571428571428575), 'C-4': np.float64(3.6571428571428575), 'D-1': np.float64(3.6571428571428575), 'D-2': np.float64(3.6571428571428575), 'D-4': np.float64(3.6571428571428575)}
water_delta:           date   A-2   A-1   A-3   A-4   B-1   B-2   B-4   B-3   C-1   C-2  \
0   2025-11-26  1.11  1.11  1.11  1.11  1.11  1.11  1.11  1.11  1.11  1.11
1   2025-11-27  1.08  1.08  1.08  1.08  1.08  1.08  1.08  1.08  1.08  1.08
2   2025-11-28  0.90  0.90  0.90  0.90  0.90  0.90  0.90  0.90  0.90  0.90
3   2025-11-29  0.78  0.78  0.78  0.78  0.78  0.78  0.78  0.78  0.78  0.78
4   2025-11-30  1.08  1.08  1.08  1.08  1.08  1.08  1.08  1.08  1.08  1.08
..         ...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
73  2026-02-07 -2.40 -2.40 -2.40 -2.40 -2.40 -2.40 -2.40 -2.40 -2.40 -2.25
74  2026-02-08 -3.10 -3.10 -3.10 -3.10 -3.10 -3.10 -3.10 -3.10 -3.10 -3.15
75  2026-02-09 -3.60 -3.60 -3.60 -3.60 -3.60 -3.60 -3.60 -3.60 -3.60 -3.80
76  2026-02-10 -3.00 -3.00 -3.00 -3.00 -3.00 -3.00 -3.00 -3.00 -3.00 -2.80
77  2026-02-11  4.50  1.75  4.50  4.50  4.50  4.50  4.50  4.50  4.50  4.50

     D-3   C-3   C-4   D-1   D-2   D-4
0   1.11  1.11  1.11  1.11  1.11  1.11
1   1.08  1.08  1.08  1.08  1.08  1.08
2   0.90  0.90  0.90  0.90  0.90  0.90
3   0.78  0.78  0.78  0.78  0.78  0.78
4   1.08  1.08  1.08  1.08  1.08  1.08
..   ...   ...   ...   ...   ...   ...
73 -2.40 -2.40 -2.25 -2.40 -2.40 -2.45
74 -3.10 -3.10 -3.15 -3.10 -3.10 -3.10
75 -3.60 -3.60 -3.80 -3.60 -3.60 -3.55
76 -3.00 -3.00 -2.80 -3.00 -3.00 -3.15
77  4.50  1.05  1.05  4.50  4.50  4.50

[78 rows x 17 columns]

/Users/omar/src/autoanton/utils.py:599: UserWarning: Dates in Kc but not in RET: [datetime.date(2025, 11, 15), datetime.date(2025, 11, 16), datetime.date(2025, 11, 17), datetime.date(2025, 11, 18), datetime.date(2025, 11, 19), datetime.date(2025, 11, 20), datetime.date(2025, 11, 21), datetime.date(2025, 11, 22), datetime.date(2025, 11, 23), datetime.date(2025, 11, 24), datetime.date(2025, 11, 25), datetime.date(2026, 2, 12), datetime.date(2026, 2, 13), datetime.date(2026, 2, 14), datetime.date(2026, 2, 15), datetime.date(2026, 2, 16), datetime.date(2026, 2, 17), datetime.date(2026, 2, 18), datetime.date(2026, 2, 19), datetime.date(2026, 2, 20), datetime.date(2026, 2, 21), datetime.date(2026, 2, 22), datetime.date(2026, 2, 23), datetime.date(2026, 2, 24), datetime.date(2026, 2, 25), datetime.date(2026, 2, 26), datetime.date(2026, 2, 27), datetime.date(2026, 2, 28)]
  warnings.warn(f"Dates in Kc but not in RET: {sorted(missing_in_ret)}")
/Users/omar/src/autoanton/utils.py:612: UserWarning: Dates missing in rainfall data: [datetime.date(2026, 2, 11)]
  warnings.warn(f"Dates missing in rainfall data: {sorted(rainfall_missing)}")

,date,A-2,A-1,A-3,A-4,B-1,B-2,B-4,B-3,C-1,C-2,D-3,C-3,C-4,D-1,D-2,D-4
0,2025-11-26,1.11,1.110,1.11,1.11,1.110,1.11,1.110,1.110,1.11,1.11,1.110,1.11,1.11,1.110,1.11,1.110
1,2025-11-27,1.08,1.080,1.08,1.08,1.080,1.08,1.080,1.080,1.08,1.08,1.080,1.08,1.08,1.080,1.08,1.080
2,2025-11-28,0.90,0.900,0.90,0.90,0.900,0.90,0.900,0.900,0.90,0.90,0.900,0.90,0.90,0.900,0.90,0.900
3,2025-11-29,0.78,0.780,0.78,0.78,0.780,0.78,0.780,0.780,0.78,0.78,0.780,0.78,0.78,0.780,0.78,0.780
4,2025-11-30,1.08,1.080,1.08,1.08,1.080,1.08,1.080,1.080,1.08,1.08,1.080,1.08,1.08,1.080,1.08,1.080
5,2025-12-01,0.99,0.990,0.99,0.99,0.990,0.99,0.990,0.990,0.99,0.99,0.990,0.99,0.99,0.990,0.99,0.990
6,2025-12-02,0.99,0.990,0.99,0.99,0.990,0.99,0.990,0.990,0.99,0.99,0.990,0.99,0.99,0.990,0.99,0.990
7,2025-12-03,0.93,0.930,0.93,0.93,0.930,0.93,0.930,0.930,0.93,0.93,0.930,0.93,0.93,0.930,0.93,0.930
8,2025-12-04,0.84,0.840,0.84,0.84,0.840,0.84,0.840,0.840,0.84,0.84,0.840,0.84,0.84,0.840,0.84,0.840
9,2025-12-05,0.84,0.840,0.84,0.84,0.840,0.84,0.840,0.840,0.84,0.84,0.840,0.84,0.84,0.840,0.84,0.840
10,2025-12-06,1.26,1.260,1.26,1.26,1.260,1.26,1.260,1.260,1.26,1.26,1.260,1.26,1.26,1.260,1.26,1.260
11,2025-12-07,2.40,2.400,2.40,2.40,2.400,2.40,2.400,2.400,2.40,3.60,2.400,2.40,3.60,2.400,2.40,2.300
12,2025-12-08,-2.80,-2.800,-2.80,-2.80,-2.800,-2.80,-2.800,-2.800,-2.80,-2.95,-2.800,-2.80,-2.95,-2.800,-2.80,-2.350
13,2025-12-09,0.50,45.500,45.50,0.50,40.500,45.50,0.500,0.500,45.50,50.40,0.500,50.50,45.40,0.500,0.50,0.400
14,2025-12-10,-2.30,9.200,9.20,-2.30,9.200,9.20,-2.300,-2.300,9.20,9.25,-2.300,9.20,9.25,-2.300,-2.30,-2.300
15,2025-12-11,42.60,9.100,9.10,0.72,9.100,9.10,42.600,37.600,9.10,9.10,0.720,9.10,9.10,0.720,0.72,0.720
16,2025-12-12,34.90,34.900,34.90,23.40,34.900,34.90,34.900,34.900,34.90,35.75,23.400,34.90,35.75,23.400,23.40,21.800
17,2025-12-13,9.50,7.500,0.60,0.60,0.600,0.60,9.500,9.500,0.60,0.60,0.600,0.60,0.60,0.600,0.60,0.600
18,2025-12-14,9.60,6.100,7.60,0.57,7.600,7.60,9.600,9.600,7.60,7.60,0.570,7.60,7.60,0.570,0.57,0.570
19,2025-12-15,0.54,7.700,0.54,43.20,0.540,0.54,0.540,0.540,0.54,0.54,0.540,0.54,0.54,0.540,0.54,0.540
20,2025-12-16,9.70,0.200,9.70,11.70,9.700,9.70,9.700,9.700,9.70,9.55,50.200,9.70,9.55,50.200,0.20,45.750
21,2025-12-17,5.90,15.400,5.90,17.40,5.900,5.90,5.900,5.900,5.90,7.30,17.400,5.90,7.30,17.400,5.90,20.250
22,2025-12-18,7.30,0.660,7.30,9.30,7.300,7.30,7.300,7.300,7.30,7.30,9.300,7.30,7.30,9.300,0.66,9.350
23,2025-12-19,1.23,3.900,1.23,1.23,1.230,1.23,1.230,1.230,1.23,1.23,7.400,1.23,1.23,7.400,45.90,7.400
24,2025-12-20,7.10,0.720,5.60,7.10,5.600,5.60,7.100,7.100,5.60,5.60,0.720,5.60,5.60,0.720,9.10,0.720
25,2025-12-21,0.63,5.900,0.63,0.63,0.630,0.63,0.630,0.630,0.63,0.63,7.400,0.63,0.63,7.400,9.40,7.400
26,2025-12-22,5.10,0.870,5.10,6.60,5.100,5.10,5.100,5.100,5.10,5.10,0.870,5.10,5.10,0.870,8.60,0.870
27,2025-12-23,1.02,4.600,1.02,6.60,1.020,1.02,1.020,1.020,1.02,1.02,6.100,1.02,1.02,6.100,1.02,6.100
28,2025-12-24,5.80,0.660,5.80,7.30,5.800,5.80,5.800,5.800,5.80,5.80,0.660,5.80,5.80,0.660,7.30,0.660
29,2025-12-25,5.70,5.700,5.70,0.69,5.700,0.69,0.690,5.700,0.69,0.69,7.200,0.69,0.69,7.200,0.69,7.200
30,2025-12-26,6.10,6.100,6.10,6.10,6.100,6.10,6.100,6.100,6.10,6.10,0.570,6.10,6.10,0.570,7.60,0.570
31,2025-12-27,0.84,5.200,0.84,0.84,0.840,0.84,0.840,0.840,0.84,0.84,5.200,0.84,0.84,5.200,0.84,5.200
32,2025-12-28,5.60,0.720,5.60,5.60,5.600,5.60,5.600,5.600,5.60,5.60,0.720,5.60,5.60,0.720,7.10,0.720
33,2025-12-29,0.87,5.100,0.87,0.87,0.870,0.87,0.870,0.870,0.87,0.87,5.100,0.87,0.87,5.100,0.87,5.100
34,2025-12-30,5.90,0.630,5.90,5.90,5.900,5.90,5.900,5.900,5.90,5.90,0.630,5.90,5.90,0.630,5.90,0.630
35,2025-12-31,0.93,4.900,0.93,0.93,0.930,0.93,0.930,0.930,0.93,0.93,4.900,0.93,0.93,4.900,0.93,4.900
36,2026-01-01,4.90,4.900,0.93,0.93,4.900,4.90,0.930,0.930,4.90,4.90,0.930,4.90,4.90,0.930,0.93,0.930
37,2026-01-02,0.66,0.660,5.80,5.80,0.660,0.66,5.800,5.800,5.80,5.80,5.800,5.80,5.80,5.800,5.80,5.800
38,2026-01-03,5.80,5.800,0.66,5.80,5.800,5.80,0.660,0.660,5.80,5.80,5.800,5.80,5.80,5.800,5.80,5.800
39,2026-01-04,0.69,0.690,5.70,5.70,0.690,0.69,0.690,0.690,5.70,5.70,0.690,5.70,5.70,0.690,0.69,0.690
40,2026-01-05,5.80,0.660,0.66,0.66,5.800,5.80,0.660,0.660,0.66,0.66,5.800,0.66,0.66,5.800,5.80,5.800
41,2026-01-06,0.63,0.630,5.90,5.90,0.630,0.63,0.630,0.630,5.90,5.90,0.630,5.90,5.90,0.630,0.63,0.630
42,2026-01-07,0.75,0.750,0.75,0.75,0.750,0.75,0.750,0.750,0.75,0.75,0.750,0.75,0.75,0.750,5.50,0.750
43,2026-01-08,0.75,0.750,5.50,5.50,5.500,5.50,5.500,5.500,5.50,5.50,5.500,5.50,5.50,5.500,0.75,5.500
44,2026-01-09,1.80,1.800,1.80,1.80,1.800,1.80,1.800,1.800,1.80,9.80,1.800,1.80,1.80,1.800,1.80,0.800
45,2026-01-10,5.40,5.400,5.40,5.40,0.780,0.78,0.780,0.780,0.78,0.78,0.780,0.78,5.40,0.780,0.78,0.780
46,2026-01-11,0.51,0.510,0.51,0.51,6.300,0.51,6.300,6.300,6.30,6.30,6.300,6.30,0.51,6.300,6.30,6.300
47,2026-01-12,1.35,1.350,1.35,1.35,1.350,1.35,1.350,1.350,1.35,1.35,1.350,1.35,1.35,1.350,1.35,1.350
48,2026-01-13,1.05,4.500,1.05,4.50,1.050,1.05,1.050,1.050,1.05,1.05,1.050,1.05,1.05,1.050,1.05,1.050
49,2026-01-14,5.50,0.750,5.50,0.75,0.750,0.75,0.750,0.750,0.75,0.75,5.500,0.75,0.75,5.500,5.50,5.500
50,2026-01-15,0.78,0.780,0.78,0.78,0.780,0.78,0.780,0.780,0.78,0.78,0.780,0.78,0.78,0.780,0.78,0.780
51,2026-01-16,0.63,0.630,0.63,0.63,0.630,0.63,0.630,0.630,0.63,0.63,0.630,0.63,0.63,0.630,0.63,0.630
52,2026-01-17,0.51,0.510,0.51,0.51,0.510,0.51,0.510,0.510,0.51,0.51,0.510,0.51,0.51,0.510,0.51,0.510
53,2026-01-18,0.66,5.800,5.80,0.66,5.800,0.66,0.660,5.800,0.66,0.66,0.660,0.66,0.66,0.660,5.80,0.660
54,2026-01-19,0.63,0.630,0.63,0.63,0.630,0.63,0.630,0.630,0.63,0.63,0.630,0.63,0.63,0.630,0.63,0.630
55,2026-01-20,0.81,0.810,0.81,0.81,0.810,0.81,0.810,0.810,0.81,0.81,0.810,0.81,0.81,0.810,0.81,0.810
56,2026-01-21,0.63,0.630,0.63,0.63,0.630,0.63,0.630,0.630,0.63,0.63,0.630,0.63,0.63,0.630,0.63,0.630
57,2026-01-22,6.90,-1.100,-1.10,6.90,-1.100,6.90,6.900,-1.100,-1.10,7.00,-1.100,-1.10,7.00,-1.100,-1.10,-1.100
58,2026-01-23,-1.50,-1.500,-1.50,-1.50,-1.500,-1.50,-1.500,-1.500,-1.50,-1.85,-1.500,-1.50,-1.85,-1.500,-1.50,-1.550
59,2026-01-24,18.60,10.600,18.60,10.60,18.600,10.60,10.600,18.600,10.60,11.35,10.600,10.60,11.35,18.600,10.60,19.300
60,2026-01-25,-1.50,-1.500,-1.50,-1.50,-1.500,-1.50,-1.500,-1.500,-1.50,-1.10,-1.500,-1.50,-1.10,-1.500,-1.50,-1.200
61,2026-01-26,0.72,0.816,0.72,0.72,0.720,0.72,0.720,0.768,0.72,0.72,0.720,0.72,0.72,0.720,0.72,0.720
62,2026-01-27,0.99,1.155,0.99,0.99,0.990,0.99,0.990,1.089,4.70,0.99,4.700,4.70,0.99,0.990,4.70,0.990
63,2026-01-28,1.08,1.296,1.08,1.08,1.116,1.08,1.080,1.224,1.08,1.08,1.080,1.08,1.08,1.080,1.08,1.080
64,2026-01-29,0.72,0.888,0.72,0.72,0.768,0.72,0.720,0.840,0.72,0.72,0.720,0.72,0.72,0.744,0.72,0.720
65,2026-01-30,0.72,0.912,0.72,0.72,0.792,0.72,0.744,0.864,0.72,0.72,0.720,0.72,0.72,0.792,0.72,0.720
66,2026-01-31,1.11,1.443,1.11,1.11,4.300,1.11,4.300,1.369,1.11,4.30,1.184,1.11,4.30,1.295,1.11,1.184
67,2026-02-01,0.93,1.240,0.93,0.93,1.085,0.93,1.085,1.178,4.90,0.93,1.054,4.90,0.93,1.147,0.93,1.054
68,2026-02-02,1.65,2.500,2.50,1.65,1.980,2.50,2.035,2.500,1.65,1.65,2.500,1.65,1.65,2.500,1.65,1.980
69,2026-02-03,4.00,1.680,1.20,4.00,1.480,1.20,1.560,1.600,1.20,1.20,1.520,1.20,1.20,1.640,4.00,4.000
70,2026-02-04,1.05,1.505,1.05,1.05,1.330,1.05,1.435,1.435,1.05,1.05,1.400,1.05,1.05,1.505,1.05,1.400
71,2026-02-05,0.72,5.600,5.60,0.72,5.600,5.60,5.600,5.600,5.60,5.60,0.984,5.60,5.60,1.056,0.72,0.984
72,2026-02-06,7.20,-0.800,-0.80,7.20,-0.800,-0.80,-0.800,-0.800,-0.80,-1.15,7.200,-0.80,-1.15,7.200,7.20,7.300
73,2026-02-07,-2.40,-2.400,-2.40,-2.40,-2.400,-2.40,-2.400,-2.400,-2.40,-2.25,-2.400,-2.40,-2.25,-2.400,-2.40,-2.450
74,2026-02-08,-3.10,-3.100,-3.10,-3.10,-3.100,-3.10,-3.100,-3.100,-3.10,-3.15,-3.100,-3.10,-3.15,-3.100,-3.10,-3.100
75,2026-02-09,-3.60,-3.600,-3.60,-3.60,-3.600,-3.60,-3.600,-3.600,-3.60,-3.80,-3.600,-3.60,-3.80,-3.600,-3.60,-3.550
76,2026-02-10,-3.00,-3.000,-3.00,-3.00,-3.000,-3.00,-3.000,-3.000,-3.00,-2.80,-3.000,-3.00,-2.80,-3.000,-3.00,-3.150
77,2026-02-11,4.50,1.750,4.50,4.50,4.500,4.50,4.500,4.500,4.50,4.50,4.500,1.05,1.05,4.500,4.50,4.500

In [11]:
df.columns

Index(['date', 'A-2', 'A-1', 'A-3', 'A-4', 'B-1', 'B-2', 'B-4', 'B-3', 'C-1',
       'C-2', 'D-3', 'C-3', 'C-4', 'D-1', 'D-2', 'D-4'],
      dtype='str')

In [ ]:
# Calculate daily water
daily_water = calculate_daily_water(daily_water_delta)

In [ ]:
# Calculate PAM root zone
pam_root_zone = calculate_pam_root_zone(daily_water, ROOT_DEPTH)

In [ ]:
# Calculate PAM depletion root zone
pam_depletion_root_zone = calculate_pam_depletion_root_zone(pam_root_zone)

In [ ]:
# Calculate moisture level and irrigation trigger
moisture_level = calculate_moisture_level(pam_root_zone)
next_irrigation = irrigation_trigger(pam_depletion_root_zone)